In [24]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [25]:
import kagglehub


# Download latest version
path = kagglehub.dataset_download("rjmanoj/credit-card-customer-churn-prediction")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction

In [26]:
df = pd.read_csv("/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [27]:
df.shape

(10000, 14)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [31]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [32]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [33]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [20]:
df.shape

(10000, 11)

In [34]:
df = pd.get_dummies(df, columns=['Geography','Gender'], drop_first=True, dtype=int)

In [35]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0,0

In [36]:
# let us scale the values first before entering it into neural network

In [42]:
X = df.drop(columns=['Exited'])
y = df['Exited']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [44]:
X_train.shape

(8000, 11)

In [45]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [46]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [48]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [66]:
#using sequential model
model = Sequential()
model.add(Dense(11,activation='relu',input_dim = 11)) #in our hidden layer we are putting 3 perceptrons which would be getting 11 inputs
model.add(Dense(11,activation='relu'))
model.add(Dense(1,activation='sigmoid')) # one output

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [67]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [68]:
model.compile(
    loss='binary_crossentropy',
    optimizer='Adam',
    metrics=[
        'accuracy',
        tensorflow.keras.metrics.Precision(),
        tensorflow.keras.metrics.Recall(),
        tensorflow.keras.metrics.AUC()
    ],
    
)

In [69]:
model.fit(X_train_scaled,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7806 - auc: 0.5340 - loss: 0.5522 - precision: 0.3072 - recall: 0.0178 - val_accuracy: 0.7975 - val_auc: 0.6858 - val_loss: 0.4709 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8011 - auc: 0.7119 - loss: 0.4566 - precision: 0.2604 - recall: 0.0034 - val_accuracy: 0.8000 - val_auc: 0.7329 - val_loss: 0.4477 - val_precision: 0.5667 - val_recall: 0.0525
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8023 - auc: 0.7497 - loss: 0.4438 - precision: 0.6937 - recall: 0.0698 - val_accuracy: 0.8125 - val_auc: 0.7524 - val_loss: 0.4361 - val_precision: 0.7143 - val_recall: 0.1235
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8191 - auc: 0.7674 - loss: 0.4225 - precision: 0.6989 - recall: 0.1592 - val_accuracy: 0.8119 - val_auc: 0.7613 - val_loss: 0.4296 - val_precision: 0.6494 - val_recall: 0.1543
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8140 - auc: 0.7646 - loss: 0.4272 - precision: 0.6563 - recall: 0.1635 - val_accuracy: 0.8175 - val_auc: 0.7686 - val_loss: 0.4241 - val_precision: 0.6538 - val_recall: 0.2099
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8251 - auc: 0.7823 - loss: 0.4156 - precision: 0.7073 - recall: 0.2454 - val_accuracy: 0.8181 - val_auc: 0.7724 - val_loss: 0.4212 - val_precision: 0.6542 - val_recall: 0.2160
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8159 - auc: 0.7837 - loss: 0.4233 - precision: 0.6749 - recall: 0.2550 - val_accuracy: 0.8194 - val_auc: 0.7759 - val_loss: 0.4192 - val_precision: 0.6636 - val_recall: 0.2191
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8319 - auc: 0.7840 - loss: 0.4108 - precision: 0.7091 - recall: 0.2859 - val_accuracy: 0.8231 - val_auc: 0.7791 - val_loss: 0.4167 - val_precision: 0.6694 - val_recall: 0.2500
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8340 - auc: 0.7936 - loss: 0.4051 - precision: 0.7207 - recall: 0.3040 - val_accuracy: 0.8238 - val_auc: 0.7796 - val_loss: 0.4162 - val_precision: 0.6944 - val_recall: 0.2315
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8247 - auc: 0.7841 - loss: 0.4224 - precision: 0.7161 - recall: 0.2997 - val_accuracy: 0.8225 - val_auc: 0.7816 - val_loss: 0.4160 - val_precision: 0.6852 - val_recall: 0.2284
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8324 - auc: 0.7928 - loss: 0.4047 - precision: 0.7237 - recall: 0.2826 - val_accuracy: 0.8219 - val_auc: 0.7826 - val_loss: 0.4151 - val_precision: 0.6726 - val_recall: 0.2346
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8406 - auc: 0.7959 - loss: 0.3896 - precision: 0.7062 - recall: 0.3031 - val_accuracy: 0.8231 - val_auc: 0.7841 - val_loss: 0.4142 - val_precision: 0.6752 - val_recall: 0.2438
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8367 - auc: 0.7850 - loss: 0.4040 - precision: 0.7208 - recall: 0.2944 - val_accuracy: 0.8219 - val_auc: 0.7867 - val_loss: 0.4129 - val_precision: 0.6667 - val_recall: 0.2407
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8395 - auc: 0.7963 - loss: 0.3922 - precision: 0.7095 - recall: 0.2864 - val_accuracy: 0.8200 - val_auc: 0.7891 - val_loss: 0.4114 - val_precision: 0.6552 - val_recall: 0.2346
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8374 - auc: 0.7997 - loss: 0.3953 - precision: 0.7174 - recall: 0.3099 - val_accuracy: 0.8200 - val_auc: 0.7901 - val_loss: 0.4105 - val_precision: 0.6525 - val_recall: 0.2377
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8294 - auc: 0.7965 - loss: 0.4023 - precision: 0.6996 - recall: 0.2829 - val_accuracy: 0.8244 - val_auc: 0.7916 - val_loss: 0.4093 - val_precision: 0.6617 - val_recall: 0.2716
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8317 - auc: 0.8066 - loss: 0.3998 - precision: 0.7351 - recall: 0.3101 - val_accuracy: 0.8213 - val_auc: 0.7934 - val_loss: 0.4088 - val_precision: 0.6727 - val_recall: 0.2284
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8405 - auc: 0.8171 - loss: 0.3870 - precision: 0.7791 - recall: 0.3091 - val_accuracy: 0.8244 - val_auc: 0.7980 - val_loss: 0.4057 - val_precision: 0.6748 - val_recall: 0.2562
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8354 - auc: 0.8116 - loss: 0.3903 - precision: 0.7174 - recall: 0.3118 - val_accuracy: 0.8288 - val_auc: 0.8015 - val_loss: 0.4027 - val_precision: 0.7016 - val_recall: 0.2685
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8376 - auc: 0.8238 - loss: 0.3859 - precision: 0.7461 - recall: 0.3283 - val_accuracy: 0.8244 - val_auc: 0.8051 - val_loss: 0.3990 - val_precision: 0.6525 - val_recall: 0.2840
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8394 - auc: 0.8173 - loss: 0.3844 - precision: 0.7104 - recall: 0.3342 - val_accuracy: 0.8281 - val_auc: 0.8122 - val_loss: 0.3934 - val_precision: 0.6899 - val_recall: 0.2747
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8473 - auc: 0.8261 - loss: 0.3783 - precision: 0.7811 - recall: 0.3570 - val_accuracy: 0.8325 - val_auc: 0.8170 - val_loss: 0.3886 - val_precision: 0.7258 - val_recall: 0.2778
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8568 - auc: 0.8356 - loss: 0.3620 - precision: 0.8016 - recall: 0.3625 - val_accuracy: 0.8325 - val_auc: 0.8234 - val_loss: 0.3823 - val_precision: 0.6842 - val_recall: 0.3210
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8528 - auc: 0.8400 - loss: 0.3678 - precision: 0.7737 - recall: 0.4210 - val_accuracy: 0.8350 - val_auc: 0.8296 - val_loss: 0.3758 - val_precision: 0.6899 - val_recall: 0.3364
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8557 - auc: 0.8544 - loss: 0.3524 - precision: 0.7780 - recall: 0.4250 - val_accuracy: 0.8363 - val_auc: 0.8356 - val_loss: 0.3713 - val_precision: 0.7183 - val_recall: 0.3148
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8575 - auc: 0.8601 - loss: 0.3492 - precision: 0.7979 - recall: 0.4294 - val_accuracy: 0.8431 - val_auc: 0.8397 - val_loss: 0.3652 - val_precision: 0.7417 - val_recall: 0.3457
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8505 - auc: 0.8468 - loss: 0.3637 - precision: 0.7917 - recall: 0.4107 - val_accuracy: 0.8444 - val_auc: 0.8424 - val_loss: 0.3628 - val_precision: 0.7483 - val_recall: 0.3488
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8600 - auc: 0.8567 - loss: 0.3457 - precision: 0.7779 - recall: 0.4319 - val_accuracy: 0.8431 - val_auc: 0.8439 - val_loss: 0.3613 - val_precision: 0.7450 - val_recall: 0.3426
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8646 - auc: 0.8584 - loss: 0.3366 - precision: 0.7908 - recall: 0.4361 - val_accuracy: 0.8506 - val_auc: 0.8451 - val_loss: 0.3576 - val_precision: 0.7429 - val_recall: 0.4012
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8641 - auc: 0.8675 - loss: 0.3350 - precision: 0.7788 - recall: 0.4692 - val_accuracy: 0.8487 - val_auc: 0.8465 - val_loss: 0.3563 - val_precision: 0.7500 - val_recall: 0.3796
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8637 - auc: 0.8592 - loss: 0.3385 - precision: 0.7814 - recall: 0.4456 - val_accuracy: 0.8500 - val_auc: 0.8478 - val_loss: 0.3550 - val_precision: 0.7333 - val_recall: 0.4074
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8652 - auc: 0.8598 - loss: 0.3325 - precision: 0.7490 - recall: 0.4592 - val_accuracy: 0.8487 - val_auc: 0.8488 - val_loss: 0.3545 - val_precision: 0.7356 - val_recall: 0.3951
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8597 - auc: 0.8604 - loss: 0.3429 - precision: 0.7684 - recall: 0.4649 - val_accuracy: 0.8519 - val_auc: 0.8481 - val_loss: 0.3539 - val_precision: 0.7458 - val_recall: 0.4074
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8628 - auc: 0.8640 - loss: 0.3349 - precision: 0.7544 - recall: 0.4771 - val_accuracy: 0.8506 - val_auc: 0.8492 - val_loss: 0.3533 - val_precision: 0.7429 - val_recall: 0.4012
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8573 - auc: 0.8613 - loss: 0.3407 - precision: 0.7475 - recall: 0.4540 - val_accuracy: 0.8531 - val_auc: 0.8473 - val_loss: 0.3538 - val_precision: 0.7432 - val_recall: 0.4198
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8569 - auc: 0.8595 - loss: 0.3428 - precision: 0.7463 - recall: 0.4696 - val_accuracy: 0.8506 - val_auc: 0.8494 - val_loss: 0.3535 - val_precision: 0.7457 - val_recall: 0.3981
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8596 - auc: 0.8656 - loss: 0.3365 - precision: 0.7586 - recall: 0.4652 - val_accuracy: 0.8537 - val_auc: 0.8485 - val_loss: 0.3527 - val_precision: 0.7500 - val_recall: 0.4167
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8670 - auc: 0.8764 - loss: 0.3235 - precision: 0.7713 - recall: 0.4848 - val_accuracy: 0.8525 - val_auc: 0.8490 - val_loss: 0.3520 - val_precision: 0.7366 - val_recall: 0.4228
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8623 - auc: 0.8691 - loss: 0.3304 - precision: 0.7611 - recall: 0.4692 - val_accuracy: 0.8519 - val_auc: 0.8500 - val_loss: 0.3520 - val_precision: 0.7514 - val_recall: 0.4012
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8719 - auc: 0.8669 - loss: 0.3193 - precision: 0.7670 - recall: 0.4630 - val_accuracy: 0.8544 - val_auc: 0.8511 - val_loss: 0.3506 - val_precision: 0.7486 - val_recall: 0.4228
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8592 - auc: 0.8590 - loss: 0.3416 - precision: 0.7712 - recall: 0.4583 - val_accuracy: 0.8544 - val_auc: 0.8524 - val_loss: 0.3507 - val_precision: 0.7486 - val_recall: 0.4228
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8590 - auc: 0.8590 - loss: 0.3454 - precision: 0.7696 - recall: 0.4785 - val_accuracy: 0.8544 - val_auc: 0.8519 - val_loss: 0.3539 - val_precision: 0.7725 - val_recall: 0.3981
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8674 - auc: 0.8781 - loss: 0.3189 - precision: 0.7877 - recall: 0.4718 - val_accuracy: 0.8569 - val_auc: 0.8508 - val_loss: 0.3497 - val_precision: 0.7596 - val_recall: 0.4290
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8658 - auc: 0.8694 - loss: 0.3303 - precision: 0.7909 - recall: 0.4696 - val_accuracy: 0.8600 - val_auc: 0.8502 - val_loss: 0.3502 - val_precision: 0.7551 - val_recall: 0.4568
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8622 - auc: 0.8724 - loss: 0.3268 - precision: 0.7517 - recall: 0.4833 - val_accuracy: 0.8525 - val_auc: 0.8522 - val_loss: 0.3499 - val_precision: 0.7500 - val_recall: 0.4074
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8586 - auc: 0.8588 - loss: 0.3422 - precision: 0.7638 - recall: 0.4602 - val_accuracy: 0.8562 - val_auc: 0.8510 - val_loss: 0.3498 - val_precision: 0.7554 - val_recall: 0.4290
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8702 - auc: 0.8737 - loss: 0.3229 - precision: 0.7839 - recall: 0.5074 - val_accuracy: 0.8556 - val_auc: 0.8518 - val_loss: 0.3485 - val_precision: 0.7435 - val_recall: 0.4383
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8630 - auc: 0.8618 - loss: 0.3351 - precision: 0.7602 - recall: 0.4701 - val_accuracy: 0.8544 - val_auc: 0.8511 - val_loss: 0.3498 - val_precision: 0.7514 - val_recall: 0.4198
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8581 - auc: 0.8758 - loss: 0.3279 - precision: 0.7509 - recall: 0.4874 - val_accuracy: 0.8556 - val_auc: 0.8518 - val_loss: 0.3499 - val_precision: 0.7460 - val_recall: 0.4352
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8687 - auc: 0.8745 - loss: 0.3214 - precision: 0.7779 - recall: 0.4895 - val_accuracy: 0.8544 - val_auc: 0.8513 - val_loss: 0.3498 - val_precision: 0.7514 - val_recall: 0.4198
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8643 - auc: 0.8614 - loss: 0.3324 - precision: 0.7763 - recall: 0.4626 - val_accuracy: 0.8594 - val_auc: 0.8506 - val_loss: 0.3500 - val_precision: 0.7513 - val_recall: 0.4568
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8685 - auc: 0.8696 - loss: 0.3230 - precision: 0.7585 - recall: 0.4890 - val_accuracy: 0.8569 - val_auc: 0.8518 - val_loss: 0.3492 - val_precision: 0.7540 - val_recall: 0.4352
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8617 - auc: 0.8654 - loss: 0.3351 - precision: 0.7695 - recall: 0.4729 - val_accuracy: 0.8506 - val_auc: 0.8519 - val_loss: 0.3526 - val_precision: 0.7485 - val_recall: 0.3951
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8651 - auc: 0.8600 - loss: 0.3343 - precision: 0.7605 - recall: 0.4778 - val_accuracy: 0.8512 - val_auc: 0.8524 - val_loss: 0.3508 - val_precision: 0.7529 - val_recall: 0.3951
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8679 - auc: 0.8775 - loss: 0.3220 - precision: 0.7915 - recall: 0.4833 - val_accuracy: 0.8587 - val_auc: 0.8517 - val_loss: 0.3492 - val_precision: 0.7526 - val_recall: 0.4506
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8689 - auc: 0.8768 - loss: 0.3183 - precision: 0.7577 - recall: 0.5088 - val_accuracy: 0.8525 - val_auc: 0.8511 - val_loss: 0.3515 - val_precision: 0.7588 - val_recall: 0.3981
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8711 - auc: 0.8746 - loss: 0.3160 - precision: 0.7974 - recall: 0.4625 - val_accuracy: 0.8594 - val_auc: 0.8512 - val_loss: 0.3498 - val_precision: 0.7438 - val_recall: 0.4660
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8683 - auc: 0.8798 - loss: 0.3217 - precision: 0.7851 - recall: 0.5090 - val_accuracy: 0.8569 - val_auc: 0.8527 - val_loss: 0.3483 - val_precision: 0.7568 - val_recall: 0.4321
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8694 - auc: 0.8689 - loss: 0.3221 - precision: 0.7682 - recall: 0.4828 - val_accuracy: 0.8569 - val_auc: 0.8511 - val_loss: 0.3486 - val_precision: 0.7540 - val_recall: 0.4352
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8669 - auc: 0.8815 - loss: 0.3190 - precision: 0.7879 - recall: 0.4956 - val_accuracy: 0.8587 - val_auc: 0.8522 - val_loss: 0.3490 - val_precision: 0.7606 - val_recall: 0.4414
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8692 - auc: 0.8750 - loss: 0.3197 - precision: 0.7756 - recall: 0.4776 - val_accuracy: 0.8562 - val_auc: 0.8505 - val_loss: 0.3501 - val_precision: 0.7640 - val_recall: 0.4198
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8688 - auc: 0.8799 - loss: 0.3129 - precision: 0.7624 - recall: 0.4830 - val_accuracy: 0.8556 - val_auc: 0.8494 - val_loss: 0.3504 - val_precision: 0.7487 - val_recall: 0.4321
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8696 - auc: 0.8790 - loss: 0.3165 - precision: 0.7707 - recall: 0.5003 - val_accuracy: 0.8525 - val_auc: 0.8512 - val_loss: 0.3511 - val_precision: 0.7558 - val_recall: 0.4012
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8672 - auc: 0.8824 - loss: 0.3171 - precision: 0.7803 - recall: 0.4944 - val_accuracy: 0.8556 - val_auc: 0.8508 - val_loss: 0.3504 - val_precision: 0.7541 - val_recall: 0.4259
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8684 - auc: 0.8772 - loss: 0.3224 - precision: 0.7906 - recall: 0.4961 - val_accuracy: 0.8575 - val_auc: 0.8508 - val_loss: 0.3490 - val_precision: 0.7449 - val_recall: 0.4506
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8658 - auc: 0.8724 - loss: 0.3266 - precision: 0.7698 - recall: 0.4883 - val_accuracy: 0.8562 - val_auc: 0.8514 - val_loss: 0.3492 - val_precision: 0.7500 - val_recall: 0.4352
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8712 - auc: 0.8726 - loss: 0.3252 - precision: 0.8009 - recall: 0.5044 - val_accuracy: 0.8537 - val_auc: 0.8516 - val_loss: 0.3505 - val_precision: 0.7647 - val_recall: 0.4012
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8668 - auc: 0.8636 - loss: 0.3298 - precision: 0.7718 - recall: 0.4792 - val_accuracy: 0.8537 - val_auc: 0.8516 - val_loss: 0.3498 - val_precision: 0.7557 - val_recall: 0.4105
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8661 - auc: 0.8811 - loss: 0.3198 - precision: 0.7685 - recall: 0.4854 - val_accuracy: 0.8569 - val_auc: 0.8512 - val_loss: 0.3486 - val_precision: 0.7387 - val_recall: 0.4537
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8656 - auc: 0.8744 - loss: 0.3253 - precision: 0.7713 - recall: 0.4888 - val_accuracy: 0.8581 - val_auc: 0.8512 - val_loss: 0.3497 - val_precision: 0.7650 - val_recall: 0.4321
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8668 - auc: 0.8786 - loss: 0.3190 - precision: 0.7689 - recall: 0.4925 - val_accuracy: 0.8575 - val_auc: 0.8498 - val_loss: 0.3497 - val_precision: 0.7553 - val_recall: 0.4383
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8652 - auc: 0.8796 - loss: 0.3250 - precision: 0.7856 - recall: 0.4957 - val_accuracy: 0.8600 - val_auc: 0.8501 - val_loss: 0.3498 - val_precision: 0.7632 - val_recall: 0.4475
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8673 - auc: 0.8828 - loss: 0.3197 - precision: 0.7841 - recall: 0.5038 - val_accuracy: 0.8550 - val_auc: 0.8507 - val_loss: 0.3500 - val_precision: 0.7644 - val_recall: 0.4105
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8655 - auc: 0.8820 - loss: 0.3214 - precision: 0.7798 - recall: 0.5022 - val_accuracy: 0.8525 - val_auc: 0.8506 - val_loss: 0.3509 - val_precision: 0.7588 - val_recall: 0.3981
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8651 - auc: 0.8787 - loss: 0.3213 - precision: 0.7858 - recall: 0.4677 - val_accuracy: 0.8575 - val_auc: 0.8509 - val_loss: 0.3497 - val_precision: 0.7667 - val_recall: 0.4259
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8727 - auc: 0.8819 - loss: 0.3099 - precision: 0.7856 - recall: 0.4931 - val_accuracy: 0.8587 - val_auc: 0.8506 - val_loss: 0.3498 - val_precision: 0.7552 - val_recall: 0.4475
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8682 - auc: 0.8764 - loss: 0.3231 - precision: 0.7710 - recall: 0.5042 - val_accuracy: 0.8569 - val_auc: 0.8514 - val_loss: 0.3493 - val_precision: 0.7513 - val_recall: 0.4383
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8675 - auc: 0.8738 - loss: 0.3234 - precision: 0.7699 - recall: 0.4872 - val_accuracy: 0.8581 - val_auc: 0.8517 - val_loss: 0.3500 - val_precision: 0.7594 - val_recall: 0.4383
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8640 - auc: 0.8726 - loss: 0.3261 - precision: 0.7728 - recall: 0.4847 - val_accuracy: 0.8556 - val_auc: 0.8500 - val_loss: 0.3513 - val_precision: 0.7657 - val_recall: 0.4136
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8722 - auc: 0.8786 - loss: 0.3162 - precision: 0.7750 - recall: 0.5068 - val_accuracy: 0.8594 - val_auc: 0.8504 - val_loss: 0.3501 - val_precision: 0.7538 - val_recall: 0.4537
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8732 - auc: 0.8815 - loss: 0.3110 - precision: 0.7771 - recall: 0.5032 - val_accuracy: 0.8550 - val_auc: 0.8489 - val_loss: 0.3513 - val_precision: 0.7473 - val_recall: 0.4290
Epoch 82/100

In [70]:
#now let us see the values of teh calculated weights and biases
model.layers[0].get_weights()

[array([[-0.11804246,  0.14254482,  0.01292267, -0.07972973, -0.04320924,
          0.5914655 ,  0.07438048, -0.04581686,  0.11904182,  0.25913298,
          0.0330843 ],
        [-0.5743897 ,  0.36105144, -0.60033476, -0.795359  ,  0.77100235,
         -0.05408982, -0.20981488, -0.91740125, -0.17059849, -0.89351946,
         -0.85672903],
        [ 0.25849473, -0.16284256, -0.03433274,  0.00830935,  0.25720167,
         -0.58257705, -0.16357361, -0.07557072, -0.05233163, -0.17399295,
          0.03645156],
        [ 0.14981335, -0.33175373, -1.0204351 ,  0.1226    ,  0.24922313,
         -0.14997144,  0.14032169,  0.71652883,  0.63027495,  0.6717265 ,
         -0.12698378],
        [ 0.7864899 ,  0.30146277,  0.15364768,  0.25570646,  0.33736604,
         -0.02846672,  0.97411865, -0.29003295,  1.1196735 ,  0.17946805,
          0.40470552],
        [-0.3817785 , -0.42821357, -0.0018794 ,  0.1311813 ,  0.21515712,
         -0.09668593, -0.25671935, -0.03850786,  0.15730774, -0.21692201,
          0.58968043],
        [ 0.02853221, -0.3564637 , -0.18647616, -0.09819953,  1.0885558 ,
          0.7215677 , -0.0246991 ,  0.41199443,  0.1276662 , -0.5463632 ,
          0.14290671],
        [-0.13964996,  0.16525559, -0.05710678, -0.03130306,  0.03795665,
          0.47584778, -0.14259253, -0.05676611,  0.19194785,  0.25646278,
         -0.15773836],
        [ 0.12583528,  0.15737292,  0.6253613 ,  0.03540887, -0.2506882 ,
          0.25628465, -0.5223634 , -0.62165403, -0.17652962, -0.30025628,
         -0.49197295],
        [ 0.34459198,  0.3832044 , -0.04490881, -1.222748  ,  0.0390454 ,
         -0.03040632, -0.38470086,  0.30148557, -0.01589054, -0.48875552,
          0.2010711 ],
        [-0.0533207 ,  0.56560594,  0.00758064,  0.05098145,  0.26646286,
         -0.04783119,  0.02128565, -0.07982631,  0.11690755,  0.31569776,
          0.14043908]], dtype=float32),
 array([ 0.42821094,  0.24910781,  0.03506809,  0.43978703,  0.2734069 ,
        -0.11922279,  0.25656533,  0.65776324, -0.60416293,  0.6924125 ,
         0.4844727 ], dtype=float32)]

In [71]:
model.layers[1].get_weights()

[array([[ 5.4915369e-01,  3.5490561e-02,  2.8043771e-01,  9.3211621e-02,
         -5.1913434e-01,  2.5070590e-01,  2.7519232e-02,  3.1653982e-01,
          3.2083753e-01,  3.8937488e-01,  3.4229505e-01],
        [ 4.3090528e-01, -9.3836153e-01,  8.0904573e-02,  1.7787859e-01,
          2.6284227e-01,  1.5680639e-01, -1.1653805e-01,  5.4988855e-01,
         -4.2453176e-01,  2.5273117e-01,  6.9024271e-01],
        [-5.5627519e-01,  6.3104111e-01,  2.0179245e-01, -5.2924752e-01,
         -3.2438669e-01, -6.7553496e-01, -1.5048946e+00,  1.9931884e-02,
          1.3300987e-01,  4.3340924e-01,  1.0337274e+00],
        [-1.8011717e-01, -2.1280265e-01, -1.8531178e-01,  8.8220380e-02,
         -7.8396492e-02, -3.1984028e-01,  2.2373749e-01,  9.0618914e-01,
          3.6942157e-01, -6.3247251e-04, -2.2930957e-01],
        [-6.1149931e-01, -6.5724391e-01, -3.1765658e-01, -4.5325267e-01,
         -1.0175400e-01, -6.6595182e-02, -1.7007960e+00, -4.3305984e-01,
          7.1646619e-01,  7.1216804e-01,  2.2572394e-01],
        [ 4.4941179e-02, -2.3756000e-01, -8.1753038e-02,  3.5491553e-01,
          2.3108949e-01, -4.5045957e-02, -2.0806684e-01,  9.9304385e-02,
          4.1745895e-01,  3.3978936e-01, -3.4032756e-01],
        [ 4.0297565e-01,  5.4635590e-01,  9.9571675e-02,  4.2021161e-01,
         -1.6875793e+00,  6.0180402e-01,  3.4457412e-02,  1.6280617e-01,
         -3.4861785e-01, -4.3625388e-02,  5.0043565e-01],
        [-8.7729114e-01,  5.9170318e-01, -1.5321426e-01,  1.5382291e-01,
         -1.5015817e-01, -5.1032156e-01,  9.0923831e-02,  3.8756436e-01,
         -6.3663048e-01,  3.4548506e-01, -9.5011866e-01],
        [ 8.5733432e-01, -2.5552338e-01,  5.5766261e-01, -5.2341503e-01,
         -1.1223205e+00,  8.6084741e-01,  2.3661040e-01, -4.9455717e-01,
          1.2961490e-01, -6.2546223e-01, -1.0432316e+00],
        [-2.5070202e-01,  7.4814945e-01,  1.6322312e-01, -3.5505988e-02,
         -3.0446881e-02, -9.9989349e-01,  2.2817194e-01,  5.6221157e-01,
          5.4727322e-01, -3.1614164e-01, -6.3917220e-01],
        [-3.3353147e-01,  3.7089139e-02,  5.2541953e-01,  2.4725735e-01,
         -6.2294090e-01, -3.8473092e-02,  2.8040719e-01,  2.0104466e-01,
          5.5489171e-01, -8.7777026e-02,  1.0823728e-01]], dtype=float32),
 array([ 0.68656516, -0.90007657,  0.05973207,  0.17306143,  1.0202754 ,
         0.5997578 ,  0.3845901 ,  0.28388172,  0.03629668, -0.08522053,
        -0.24821569], dtype=float32)]

In [72]:
model.layers[1].get_weights()

[array([[ 5.4915369e-01,  3.5490561e-02,  2.8043771e-01,  9.3211621e-02,
         -5.1913434e-01,  2.5070590e-01,  2.7519232e-02,  3.1653982e-01,
          3.2083753e-01,  3.8937488e-01,  3.4229505e-01],
        [ 4.3090528e-01, -9.3836153e-01,  8.0904573e-02,  1.7787859e-01,
          2.6284227e-01,  1.5680639e-01, -1.1653805e-01,  5.4988855e-01,
         -4.2453176e-01,  2.5273117e-01,  6.9024271e-01],
        [-5.5627519e-01,  6.3104111e-01,  2.0179245e-01, -5.2924752e-01,
         -3.2438669e-01, -6.7553496e-01, -1.5048946e+00,  1.9931884e-02,
          1.3300987e-01,  4.3340924e-01,  1.0337274e+00],
        [-1.8011717e-01, -2.1280265e-01, -1.8531178e-01,  8.8220380e-02,
         -7.8396492e-02, -3.1984028e-01,  2.2373749e-01,  9.0618914e-01,
          3.6942157e-01, -6.3247251e-04, -2.2930957e-01],
        [-6.1149931e-01, -6.5724391e-01, -3.1765658e-01, -4.5325267e-01,
         -1.0175400e-01, -6.6595182e-02, -1.7007960e+00, -4.3305984e-01,
          7.1646619e-01,  7.1216804e-01,  2.2572394e-01],
        [ 4.4941179e-02, -2.3756000e-01, -8.1753038e-02,  3.5491553e-01,
          2.3108949e-01, -4.5045957e-02, -2.0806684e-01,  9.9304385e-02,
          4.1745895e-01,  3.3978936e-01, -3.4032756e-01],
        [ 4.0297565e-01,  5.4635590e-01,  9.9571675e-02,  4.2021161e-01,
         -1.6875793e+00,  6.0180402e-01,  3.4457412e-02,  1.6280617e-01,
         -3.4861785e-01, -4.3625388e-02,  5.0043565e-01],
        [-8.7729114e-01,  5.9170318e-01, -1.5321426e-01,  1.5382291e-01,
         -1.5015817e-01, -5.1032156e-01,  9.0923831e-02,  3.8756436e-01,
         -6.3663048e-01,  3.4548506e-01, -9.5011866e-01],
        [ 8.5733432e-01, -2.5552338e-01,  5.5766261e-01, -5.2341503e-01,
         -1.1223205e+00,  8.6084741e-01,  2.3661040e-01, -4.9455717e-01,
          1.2961490e-01, -6.2546223e-01, -1.0432316e+00],
        [-2.5070202e-01,  7.4814945e-01,  1.6322312e-01, -3.5505988e-02,
         -3.0446881e-02, -9.9989349e-01,  2.2817194e-01,  5.6221157e-01,
          5.4727322e-01, -3.1614164e-01, -6.3917220e-01],
        [-3.3353147e-01,  3.7089139e-02,  5.2541953e-01,  2.4725735e-01,
         -6.2294090e-01, -3.8473092e-02,  2.8040719e-01,  2.0104466e-01,
          5.5489171e-01, -8.7777026e-02,  1.0823728e-01]], dtype=float32),
 array([ 0.68656516, -0.90007657,  0.05973207,  0.17306143,  1.0202754 ,
         0.5997578 ,  0.3845901 ,  0.28388172,  0.03629668, -0.08522053,
        -0.24821569], dtype=float32)]

In [74]:
X_test_scaled = scaler.transform(X_test)

In [75]:

model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([[0.02200434],
       [0.06142683],
       [0.14823647],
       ...,
       [0.0025787 ],
       [0.01850398],
       [0.261202  ]], dtype=float32)

In [76]:
# now these are teh sigmoid probabilities , we now have to decide a threshold , above which there will be one and below which there will be zero
y_log = model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [78]:
y_pred = np.where(y_log>0.5,1,0)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [80]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.865